spring:
  application:
    name: microservice-eureka
  profiles:
    active: ${PROFILES.ACTIVE:peer1}
eureka:
  client:
      service-url:
        defaultZone: http://192.168.211.160:8762/eureka/,http://192.168.211.160:8761/eureka/

---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2