spring:
  application:
    name: microservice-eureka
#  profiles:
#    active: ${PROFILES.ACTIVE:peer1}
eureka:
  client:
      service-url:
        defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
      fetch-registry: false
      register-with-eureka: false
#---
#spring:
#  profiles: peer1
#server:
#  port: 8761
#eureka:
#  instance:
#    hostname: peer1
#---
#spring:
#  profiles: peer2
#server:
#  port: 8762
#eureka:
#  instance:
server:
  port: 8761
#    hostname: peer2